security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

    jwt_auth:
      pattern: ^/auth
      stateless: true
      json_login:
        username_path: email
        check_path: jwt_auth
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

  access_control:
    - { path: ^/api/markers/location, roles: PUBLIC_ACCESS }
    - { path: ^/api/markers/\d+, roles: PUBLIC_ACCESS }
    - { path: ^/api/user/add, roles: PUBLIC_ACCESS }
    - { path: ^/api/user/auth, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
